# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

fluent-bit:
  enabled: false

  existingConfigMap: "fluent-bit-config"
  openSearchHost: "opensearch"
  openSearchPort: 9200

  env:
  - name: OPENSEARCH_USERNAME
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-credentials
        key: username
  - name: OPENSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-credentials
        key: password

  dnsPolicy: ClusterFirstWithHostNet
  fullnameOverride: "fluent-bit"
  hostNetwork: true

  extraVolumeMounts:
  - name: db
    mountPath: "/var/lib/fluent-bit/db"
    readOnly: false

  extraVolumes:
    - name: db
      hostPath:
        path: /var/lib/fluent-bit/db
        type: DirectoryOrCreate

  rbac:
    nodeAccess: true

  resources:
    limits:
      cpu: 100m
      memory: 150Mi
    requests:
      cpu: 25m
      memory: 125Mi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10000

  testFramework:
    enabled: false

  initContainers:
  - name: set-volume-ownership
    image: busybox
    command: ["sh", "-c", "chown -R 10000:10000 /var/lib/fluent-bit/db"]
    resources:
      limits:
        cpu: 15m
        memory: "32Mi"
      requests:
        cpu: 10m
        memory: "24Mi"
    securityContext:
      capabilities:
        drop:
        - ALL
      privileged: true
      readOnlyRootFilesystem: true
      runAsUser: 0
    volumeMounts:
    - name: db
      mountPath: /var/lib/fluent-bit/db


openSearch:
  enabled: true

  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: ThisIsTheOpenSearchPassword1

  nameOverride: "opensearch"

  image:
    tag: "3.3.0"

  masterService: opensearch

  rbac:
    create: true
    serviceAccountName: "opensearch"

  singleNode: true


## -----------------------------------------------------------
## Values for OpenChoreo specific customizations and workloads
## -----------------------------------------------------------

openSearchCluster:
  enabled: false

  bootstrap:
    resources:
      limits:
        cpu: 1000m
        memory: 1000Mi
      requests:
        cpu: 100m
        memory: 1000Mi

  general:
    setVMMaxMapCount: true
    version: 3.3.0

  dashboards:
    enable: false
    replicas: 1
    version: 3.3.0

  nodePools:
    data:
      replicas: 2
      diskSize: 5Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
        requests:
          cpu: 100m
          memory: 1000Mi

    master:
      replicas: 3
      diskSize: 1Gi
      resources:
        limits:
          cpu: 1000m
          memory: 900Mi
        requests:
          cpu: 100m
          memory: 900Mi

  credentialsSecretName: ""
  adminPassword: ""

  internalUsers: |
    # This is the internal user database
    # The hash value is a bcrypt hash and can be generated with plugin/tools/hash.sh

    _meta:
      type: "internalusers"
      config_version: 2

    admin:
      hash: "%s"
      reserved: true
      backend_roles:
      - "admin"
      description: "Admin user"

openSearchSetup:
  enabled: true
  image:
    repository: "ghcr.io/openchoreo/observability-logs-opensearch-setup"
  openSearchSecretName: ""

  alertingWebhookUrl: "http://observer-internal.openchoreo-observability-plane:8081/api/v1alpha1/alerts/webhook"

  dataRetentionTime:
    containerLogs: "30d"
    rcaReports: "90d"
